title: Levis portfolio
description: this is a collections of projects that i have done in the past two years
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
